# Split the Data

In [ ]:
import os
from google.colab import drive

In [ ]:
gdrive_dir = '/content/drive/'

drive.mount(gdrive_dir, force_remount=True)

Mounted at /content/drive/

In [ ]:
for dirname, _, filenames in os.walk('/content/drive/MyDrive/Colab Notebooks/IntroductionToML/Data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/content/drive/MyDrive/Colab Notebooks/IntroductionToML/Data/TitanicDataset/train.csv
/content/drive/MyDrive/Colab Notebooks/IntroductionToML/Data/TitanicDataset/test.csv
/content/drive/MyDrive/Colab Notebooks/IntroductionToML/Data/TitanicDataset/gender_submission.csv

In [ ]:
# Import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
# Import the dataset
titanic = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IntroductionToML/Data/TitanicDataset/train.csv')

In [ ]:
# Peek at the data
titanic.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
# Train, validation, test sets split
features = titanic.drop('Survived', axis=1)
labels = titanic['Survived']

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.4, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

In [ ]:
# Check data allocation
print(len(labels), len(y_train), len(y_val), len(y_test))

891 534 179 178